% Test the cell array syntax issue
fprintf('Testing cell array definition...\n');

try
    % Test the problematic cell array definition
    generalPerformanceMetrics = {
        'TotalWorkingDays', 'TotalCases', 'AvgCasesPerDay', 'MedianCasesPerDay', 'StdCasesPerDay', ...
        'AvgIdleTimePerDay', 'MedianIdleTimePerDay', 'StdIdleTimePerDay', ...
        'P25IdleTimePerDay', 'P75IdleTimePerDay', 'P90IdleTimePerDay', ...
        'AvgOvertimePerDay', 'MedianOvertimePerDay', 'StdOvertimePerDay', ...
        'AvgWorkTimePerDay', 'MedianWorkTimePerDay', ...
        'AvgFlipToTurnoverRatio', 'MedianFlipToTurnoverRatio', 'StdFlipToTurnoverRatio', ...
        'P25FlipToTurnoverRatio', 'P75FlipToTurnoverRatio', 'P90FlipToTurnoverRatio', ...
        'AvgCasesPerHour', 'UtilizationRate', ...
        'AvgIdleTimePerTurnover', 'MedianIdleTimePerTurnover', 'StdIdleTimePerTurnover', ...
        'MultiProcedureDays', 'MultiProcedureDaysPct', 'DaysWithOvertime', 'DaysWithOvertimePct', ...
        'InpatientCases', 'OutpatientCases', 'InpatientProportion', 'OutpatientProportion', ...
        'UniqueProcedureTypes', 'ProcedureDiversityIndex', ...
        'AvgProcedureTime', 'MedianProcedureTime', 'StdProcedureTime', ...
        'AvgSetupTime', 'MedianSetupTime', 'StdSetupTime', ...
        'AvgPostTime', 'MedianPostTime', 'StdPostTime'
    };
    
    fprintf('Cell array created successfully with %d elements\n', length(generalPerformanceMetrics));
    
catch ME
    fprintf('Error: %s\n', ME.message);
    fprintf('Identifier: %s\n', ME.identifier);
end